# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  host: localhost
  adapter: postgresql
  port: 5432
  encoding: unicode
  database: postgres
  pool: 5
  username: dannygaeta
  password: mula2010

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5433

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  encoding: unicode
  database: f_app_test
  pool: 5
  username: f_app
  password:

production:
  adapter:  postgresql
  encoding: unicode
  pool: 5
  database: dvnohr896v6d
  username: u742asv9g7ie0j
  password: p4u55tu44arevo545kc1j2uvi1n
  host: ec2-54-235-254-188.compute-1.amazonaws.com
  port: 6402