require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AwsPicturesController do

  # This should return the minimal set of attributes required to create a valid
  # AwsPicture. As you add validations to AwsPicture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AwsPicturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all aws_pictures as @aws_pictures" do
      aws_picture = AwsPicture.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aws_pictures).should eq([aws_picture])
    end
  end

  describe "GET show" do
    it "assigns the requested aws_picture as @aws_picture" do
      aws_picture = AwsPicture.create! valid_attributes
      get :show, {:id => aws_picture.to_param}, valid_session
      assigns(:aws_picture).should eq(aws_picture)
    end
  end

  describe "GET new" do
    it "assigns a new aws_picture as @aws_picture" do
      get :new, {}, valid_session
      assigns(:aws_picture).should be_a_new(AwsPicture)
    end
  end

  describe "GET edit" do
    it "assigns the requested aws_picture as @aws_picture" do
      aws_picture = AwsPicture.create! valid_attributes
      get :edit, {:id => aws_picture.to_param}, valid_session
      assigns(:aws_picture).should eq(aws_picture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AwsPicture" do
        expect {
          post :create, {:aws_picture => valid_attributes}, valid_session
        }.to change(AwsPicture, :count).by(1)
      end

      it "assigns a newly created aws_picture as @aws_picture" do
        post :create, {:aws_picture => valid_attributes}, valid_session
        assigns(:aws_picture).should be_a(AwsPicture)
        assigns(:aws_picture).should be_persisted
      end

      it "redirects to the created aws_picture" do
        post :create, {:aws_picture => valid_attributes}, valid_session
        response.should redirect_to(AwsPicture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aws_picture as @aws_picture" do
        # Trigger the behavior that occurs when invalid params are submitted
        AwsPicture.any_instance.stub(:save).and_return(false)
        post :create, {:aws_picture => { "name" => "invalid value" }}, valid_session
        assigns(:aws_picture).should be_a_new(AwsPicture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AwsPicture.any_instance.stub(:save).and_return(false)
        post :create, {:aws_picture => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aws_picture" do
        aws_picture = AwsPicture.create! valid_attributes
        # Assuming there are no other aws_pictures in the database, this
        # specifies that the AwsPicture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AwsPicture.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => aws_picture.to_param, :aws_picture => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested aws_picture as @aws_picture" do
        aws_picture = AwsPicture.create! valid_attributes
        put :update, {:id => aws_picture.to_param, :aws_picture => valid_attributes}, valid_session
        assigns(:aws_picture).should eq(aws_picture)
      end

      it "redirects to the aws_picture" do
        aws_picture = AwsPicture.create! valid_attributes
        put :update, {:id => aws_picture.to_param, :aws_picture => valid_attributes}, valid_session
        response.should redirect_to(aws_picture)
      end
    end

    describe "with invalid params" do
      it "assigns the aws_picture as @aws_picture" do
        aws_picture = AwsPicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AwsPicture.any_instance.stub(:save).and_return(false)
        put :update, {:id => aws_picture.to_param, :aws_picture => { "name" => "invalid value" }}, valid_session
        assigns(:aws_picture).should eq(aws_picture)
      end

      it "re-renders the 'edit' template" do
        aws_picture = AwsPicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AwsPicture.any_instance.stub(:save).and_return(false)
        put :update, {:id => aws_picture.to_param, :aws_picture => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aws_picture" do
      aws_picture = AwsPicture.create! valid_attributes
      expect {
        delete :destroy, {:id => aws_picture.to_param}, valid_session
      }.to change(AwsPicture, :count).by(-1)
    end

    it "redirects to the aws_pictures list" do
      aws_picture = AwsPicture.create! valid_attributes
      delete :destroy, {:id => aws_picture.to_param}, valid_session
      response.should redirect_to(aws_pictures_url)
    end
  end

end
